import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "@/trpc/react";
import Navbar from "./components/ui/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" style={{ scrollBehavior: "smooth" }}>
        <body className={`font-sans ${inter.variable} scroll-smooth`}>
          <TRPCReactProvider>
            <Navbar />

            {children}
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
